site_name: 'Backstage'
site_description: 'Main documentation for Flask Python App'
repo_url: https://github.com/AWSAgenticAI/argocd-flaskap
edit_uri: edit/main/docs
plugins:
  - techdocs-core
nav:
  - Overview:
      - Getting: 'docs/index.md'
